### ISSUE TITLE
Le bot ne réagit pas toujours aux messages/réagit mal

### ISSUE THREAD

**Issue by Amustache** [CLICGameStarProjects/ICeLAN-Telegram#2]
Exemple:
- Quel anim ? 🤖 
- x
-  . 🤖 
- x
- ... 🤖 
- y
- cool 🤖 
ensuite lorsque l'on appelle /anims
les anims proposées sont : 
- x
- y

**Comment by s314cy** [comment]
de ce que j'ai cru comprendre, le bot ne répondait pas systématiquement car son flow d'updates était perturbé par l'envoi d'une commande alors qu'une conversation était en cours

j'ai corrigé la supposée source du problème en ajoutant un handler dans les fallbacks des conversations, qui interrompt la conversation

ledit handler est activé lors de l'envoi d'une commande, les autres handlers de la conversation ne sont explicitement pas activés lors de l'envoi d'une commande

pour finir, les handlers stateless, par opposition à ceux des conversations, ont été tous mis dans un groupe de handlers à part, à priorité moindre

de ce fait, le bot va d'abord activer 0 ou 1 handler du groupe 0 (les conversations), et ensuite 0 ou 1 handler du groupe 1 (les commandes stateless), afin d'éviter tout conflit tout en activant tout de même la commande entrée en pleine conversation
